# A sample TOML config file.
[dbsession]
h="localhost:27017"
d="chbuild"
u="tmplbuild"
p="@tmpbu.sex"
[dbchbuild]
h="localhost:27017"
d="chbuild"
u="tmplbuild"
p="@tmpbu.sex"
[config]
domainallow="localhost.com,x.localhost,duyhf.noip.me,client.template.localhost"
clienttemplatedomain="client.template.localhost"
#=====demo account
demouser="demodata"
demouserpass="xyz"
#proxy="http://127.0.0.1:8866"
mainserver="http://x.localhost/"
hostname="http://b.localhost/"
templatepath="./templates/"
sameurllimit=1
#limit request in 3s
requestlimit=500
zipfileextallow=".ico,.jpg,.jpeg,.png,.gif,.txt,.html,.js,.css,.eot,.svg,.ttf,.woff,.woff2,.otf"